<ul id="theme_select">
    <li>default</li>
    <li>3024-day</li>
    <li>3024-night</li>
    <li>abcdef</li>
    <li>ambiance</li>
    <li>base16-dark</li>
    <li>base16-light</li>
    <li>bespin</li>
    <li>blackboard</li>
    <li>cobalt</li>
    <li>colorforth</li>
    <li>dracula</li>
    <li>duotone-dark</li>
    <li>duotone-light</li>
    <li>eclipse</li>
    <li>elegant</li>
    <li>erlang-dark</li>
    <li>hopscotch</li>
    <li>icecoder</li>
    <li>isotope</li>
    <li>lesser-dark</li>
    <li>liquibyte</li>
    <li>material</li>
    <li>mbo</li>
    <li>mdn-like</li>
    <li>midnight</li>
    <li>monokai</li>
    <li>neat</li>
    <li>neo</li>
    <li>night</li>
    <li>panda-syntax</li>
    <li>paraiso-dark</li>
    <li>paraiso-light</li>
    <li>pastel-on-dark</li>
    <li>railscasts</li>
    <li>rubyblue</li>
    <li>seti</li>
    <li>solarized dark</li>
    <li>solarized light</li>
    <li>the-matrix</li>
    <li>tomorrow-night-bright</li>
    <li>tomorrow-night-eighties</li>
    <li>ttcn</li>
    <li>twilight</li>
    <li>vibrant-ink</li>
    <li>xq-dark</li>
    <li>xq-light</li>
    <li>yeti</li>
    <li>zenburn</li>
</ul>